version: '3'
services:
  api:
    container_name: starter-app-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: 'mongo:4'
    ports:
      - "27017:27017"
    volumes:
      - ~/projects/data/dev:/data/db